### ISSUE TITLE
Aggregation tracks and run nfct_destroy break right functionality for iptables state ESTABLESHED

### ISSUE THREAD

**Issue by netaskd** [AGProjects/mediaproxy#5]
Hello,
I have the issue with properly work nf_conntrack for handle ESTABLESHED connection allowing port when RTP streams bridged via mediaproxy. As I see, mediaproxy aggregate two "track" of conntrack to one and drop original two "tracks" via nfct_destroy. So, remote UA port not allowed, becasue iptables cannot detects right port for allow it. Please see attachements for more info.

[conntrack_snippet.txt](https://github.com/AGProjects/mediaproxy/files/1527276/conntrack.txt)

![rtpstream](https://user-images.githubusercontent.com/1027361/33555871-fb7dfbc4-d912-11e7-83ba-f15fa840105a.png)

**Comment by danpascu** [comment]
I'm sorry, but I do not understand what you're saying.

Mediaproxy doesn't aggregate any streams like you suggest. The 2 tracks you provide in your sample are from different endpoints and thus they are meant to be handled separately, not aggregated. One endpoint send RTP and thus it established the conntrack rule, while the other didn't and propably the 2nd conntrack timed out.

There is not enough information to say exactly why the 2nd rule was deleted.
