### ISSUE TITLE
Can MediaProxy bridge between different IP networks or interfaces?

### ISSUE THREAD

**Issue by tangshiixang** [AGProjects/mediaproxy#6]
In my deployment scenario, Freeswitch ，Opensips and MediaProxy is on the same LAN .I want MediaProxy listening a public ip for Nat-ed Clients,  and a private ip for Freeswitch(Because Freeswitch can not communicate with the public ip).

**Comment by wangganglab** [comment]
Hi, guys , Have you finished this problem?  i use the mediaprxoy-2.6 version  , i was found the code was in the got_command function which file is relay.py

**Comment by adigeo** [comment]
It is not possible to relay between different interfaces.
