### ISSUE TITLE
Conntrack rules not used

### ISSUE THREAD

**Issue by adrien-martin** [AGProjects/mediaproxy#7]
Hello,
With a 4.19 kernel the conntrack rules seem not to be used.
Mediaproxy relay packets during 60s and then the session is terminated.

I see the rules in /proc/net/nf_conntrack initialized with the 60s with the state [UNREPLIED], no packets are incremented.

This didn't occur with 4.9 kernel and before.

This is probably not a bug in mediaproxy, I'm not really sure how conntrack should be working and if it could be some intended change.

NB : in a test with a custom iptables DNAT rule matching Mediaproxy, the rule is updated and used (packet counter increase, state [ASSURED], no timeout).

**Comment by adigeo** [comment]
See 

https://github.com/torvalds/linux/commit/ba3fbe663635ae7b33a2d972c5d2def036258e42
